<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
</head>
<body>





   
<form action="../controllers/connexion.php" method="post">


<input type="text" name="pseudo" required placeholder="Email">

<input type="password" name="password" required placeholder="Password">

<button type="submit"> Se connecter </button>

</form>

  

    
</body>
</html>