<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <a href="../accueil.php"></a>
    </header>

    <form action="../controllers/devisDetails.php" method="Post">


   


 
      
       <input type="text" name="titre" placeholder="Entrez ici le nom du produit"> 

        <input type="text" name="quantite"  placeholder="quantité">

         <input type="text" name="prix" placeholder="Entrez ici le prix unitaire"> 

     
        
         <label for="tva"> Tva</label> 

         <select name="tva">


         <option>20%</option>
         <option>5,5%</option>
         

         </select>


         
         <label for="devis">Pour quelle devis ?</label> 

         <select name="devis">

         <?php foreach ($tabDevis as $devis):?>


         <option value="<?= htmlspecialchars($devis['Id_devis'])?>"><?= htmlspecialchars($devis['numero_devis'])?></option>

         <?php endforeach ?>
         
         </select>
         <input type="submit" value="valider">
</form>

    
</body>
</html>