<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <a href="../accueil.php"></a>
    </header>

    <form action="../controllers/devis.php" method="Post">



 <input type="text" name="num" placeholder="Entrez ici le num de devis"> 

 <label for="dateEmission">Date d'emission</label>

 <input type="date" name="dateEmission">

 <textarea name="commentaire"></textarea>
 
 <input type="text" name="adresseFacturation" placeholder="adresse Facturation">

 <input type="submit" value="valider">



   
</form>

    
</body>
</html>