<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Création de compte</title>
</head>
<body>





   
<form action="../controllers/inscription.php" method="post">


<input type="text" name="pseudo" required placeholder="Pseudo" >

<input type="name" name="password" required placeholder="Password">

<button type="submit"> créer un compte </button>

</form>

  

    
</body>
</html>