<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Création de compte</title>
</head>
<body>





   
<form action="" method="post">


<input type="text" name="nom" required placeholder="Nom">

<input type="text" name="prenom" required placeholder="Prènom">

<input type="text" name="reference" required placeholder="numéro de reference du vendeur">

<input type="text" name="phone" required placeholder="numéro de télèphone">

<input type="mail" name="mail" required placeholder="e-mail qui servira de login">

<input type="name" name="password" required placeholder="Password">

<button type="submit"> créer un compte </button>

</form>



   
<form action="" method="post">

<input type="text" name="nom" required placeholder="Nom de la société ou de l'entreprise">

<input type="text" name="adresse" required placeholder="Adresse de l'entreprise ou de la sociétè">

<input type="text" name="phone" required placeholder="télèphone">

<button type="submit"> valider les informations </button>

</form>
  

    
</body>
</html>