<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../ressources/pageConnectée.css" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">


    <title>Document</title>
</head>
<body>
    <div class="container">
        <p> Dashboard</p>

        <button class="button2" type="submit" value="Home"><a href="../controllers/accueil.php"><i class="fas fa-home"></i> &nbsp Accueil</a></button><br>  
        <button class="button" type="submit" value="Créer un Devis"><a href="../controllers/devis.php">Créer un Devis</a></button><br>       
        <button class="button" type="submit" value="Créer une Facture"><a href="../controllers/facture.php">Créer une Facture</a></button><br>
        <button class="button" type="submit" value="Liste des Factures"><a href="">Liste des Factures</a></button><br>
        <button class="button" type="submit" value="Liste des Devis"><a href="">Liste des Devis</a></button><br>
        <button class="button" type="submit" value="Accéder à l'Agenda"><a href="">Accéder à l'Agenda</a></button><br>

    </div>
</body>
</html>








