<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../ressources/vue.css">
	<title>Devis</title>
</head>
<body>
	<div class="container">
	<header>
		<div class="societe"><?=htmlspecialchars($nameSoc['nom'])?></div>
		

		<div class="devis">Facture n°<?=htmlspecialchars($vueFacture['numero_facture'])?></div>

		
		
	</header>


	<section class="ref">
		<div class="designation">
			<div class="reference"></div>
			<div class="date"></div>
			<div class="numeroClient"></div>
		</div>

		<div class="client"></div>
	</section>

	<section class="int">
		<div class="intitule"></div>
		<div class="tableauInt">
			<table>
				<thead>
				<tr>
					<th colspan="5">Intitulé : Description du projet et/ou Produit facturé</th>
				</tr>
				</thead>
				<tbody>

				<?php foreach ($vueDetailsFacture as $details) :?>
					<tr>
						<td>Réf.<?= htmlspecialchars($details['ref_produit'])?></td>
						<td>Quantité<?= htmlspecialchars($details['quantite'])?></td>
						<td>Désignation <?= htmlspecialchars($details['nom'])?></td>
						<td>Prix unitaire HT= <?= htmlspecialchars($details['prix_unitaire'])?>€</td>
						<td>tva : <?= htmlspecialchars($details['TVA'])?>%</td>
						<td>Prix total HT <?= htmlspecialchars($details['prixTotal'])?></td>
						<td>Prix total TTC <?= htmlspecialchars($details['prixTTC'])?></td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>

		</div>
	</section>

	<section class="prix">
		<table>
		
				<tr>
					<td>Total Hors Taxe</td>
					<td class="HT">€</td>
				</tr>				
				<tr>

					<td>TVA à 20%</td>
					

					<td class="TVA"><?=$add ?></td>
					

				</tr>				
				<tr>
					<td> <strong>Total TTC en euros</strong></td>
					<td class="TTC"><strong>€</strong></td>
				</tr>
				
		</table>
	</section>

	
	
</body>
</html>