<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../ressources/vue.css">
	<title>Devis</title>
</head>

<body>

	<header>
		<h1><?= htmlspecialchars($nameSoc['nom']) ?></h1>


		<h1>Facture n°<?= htmlspecialchars($vueFacture['numero_facture']) ?></h1>

	</header>

	


	<section class="tableau">

	<div class="adresse">
		<p>Adresse Société:</p>
		<p>Code-Postal:</p>
		<p>téléphone Société:</p>

	</div>
<div class="coordonnées">
	<div>
		<p>ref client:</p>
		<p>Date:</p>
		<p>téléphone:</p>

	</div>

	<div>

	<h1>Société et ou nom du client</h1>
		<p>Adresse et code postale:</p>
		<p>téléphone:</p>

	</div>

</div>

		<div class="tableauInt">
			<table>
			<caption>Intitulé : Description du projet et/ou Produit facturé</caption>
				
				<thead>
					<tr>
						<th>Réf.</th>
						<th>Quantité</th>
						<th>Désignation </th>
						<th>Prix unitaire HT</th>
						<th>tva : </th>
						<th>Prix total HT </th>
						<th>Montant TVA </th>
						<th>Prix total TTC </th>

					</tr>
				</thead>
				

				<tbody>
					<?php foreach ($vueDetailsFacture as $details) : ?>
						<tr>
							<td><?= ($details['ref_produit']) ?></td>
							<td><?= ($details['quantite']) ?></td>
							<td><?= ($details['nom']) ?></td>
							<td><?= ($details['prix_unitaire']) ?>€</td>
							<td><?= ($details['TVA']) ?>%</td>
							<td><?= ($details['prixTotal']) ?>€</td>
							<td><?= (sprintf('%10.2f €', $details['montantTVA'])) ?></td>
							<td><?= (sprintf('%10.2f €', $details['prixTTC'])) ?></td>

						</tr>
					<?php endforeach ?>
				</tbody>

			

			</table>

		</div>


		<div class="tabPrix">
			<table>

				<tr>
					<td>Total Hors Taxe</td>
					<td class="HT"><?= sprintf('%10.2f €', $THT) ?></td>
				</tr>
				<tr>

					<td>TVA à 20%</td>


					<td class="TVA"><?= sprintf('%10.2f €', $tvaTotal) ?></td>


				</tr>

				<tr>

					<td>TVA à 5,5%</td>

					<td class="TVA"><?= sprintf('%10.2f €', $tvaTotal5) ?></td>

				</tr>
				<tr>
					<td> <strong>Total TTC en euros</strong></td>
					<td class="TTC"><strong><?= sprintf('%10.2f €', $TTC) ?></strong></td>
				</tr>

			</table>

		</div>
	</section>



</body>

</html>