<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="../ressources/vue.css">
	<title>Devis</title>
</head>
<body>
	<div class="container">
	<header>
		<div class="societe"><?=htmlspecialchars($nameSoc['nom'])?></div>
		

		<div class="devis">Facture n°<?=htmlspecialchars($vueFacture['numero_facture'])?></div>

		
		
	</header>


	<section class="ref">
		<div class="designation">
			<div class="reference"></div>
			<div class="date"></div>
			<div class="numeroClient"></div>
		</div>

		<div class="client"></div>
	</section>

	<section class="int">
		<div class="intitule"></div>
		<div class="tableauInt">
			<table>
				<thead>
				<tr>
					<th colspan="5">Intitulé : Description du projet et/ou Produit facturé</th>
				</tr>
				</thead>
				<tbody>

				<?php foreach ($vueDetailsFacture as $details) :?>
					<tr>
						<td>Réf.<?= htmlspecialchars($details['ref_produit'])?></td>
						<td>Quantité<?= htmlspecialchars($details['quantite'])?></td>
						<td>Désignation <?= htmlspecialchars($details['nom'])?></td>
						<td>Prix unitaire HT= <?= htmlspecialchars($details['prix_unitaire'])?>€</td>
						<td>tva : <?= htmlspecialchars($details['TVA'])?>%</td>
						<td>Prix total HT</td>
					</tr>
					<?php endforeach ?>
				</tbody>
			</table>

		</div>
	</section>

	<section class="prix">
		<table>
		
				<tr>
					<td>Total Hors Taxe</td>
					<td class="HT">€</td>
				</tr>				
				<tr>

                <?php foreach ($vueDetailsFacture as $details) :?>
				<?php if(count($vueDetailsFacture['TVA'])>0 && $vueDetailsFacture['TVA']=20.0):?>
					<td>TVA à 20%</td>
					

					<td class="TVA"><?= ++$add ?></td>
					<?php endif ?>
				</tr>				
				<tr>
					<td> <strong>Total TTC en euros</strong></td>
					<td class="TTC"><strong>€</strong></td>
				</tr>
				
		</table>
	</section>

	<section class="Conditions">
		<div class="texte">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dignissim dignissim luctus. Fusce molestie nec est consectetur placerat. Nulla leo ante, blandit at enim id, tincidunt tristique ipsum. Aliquam pulvinar eu eros in faucibus. Etiam sit amet est felis. Donec feugiat ex eu dolor commodo, ultrices auctor nibh consequat. Suspendisse potenti. Mauris venenatis sem velit, sit amet volutpat nisl laoreet eget. Etiam sit amet bibendum nunc, sit amet porttitor erat.</div>
		
	</section>

	<footer>
		<div class="siret">Suspendisse potenti. Mauris venenatis sem velit, sit amet volutpat nisl laoreet eget. Etiam sit amet bibendum nunc, sit amet porttitor erat.</div>
	</footer>
	</div>
	
</body>
</html>